/* It had generated by DirectStruct v1.6.1 */
#include "IDL_xml.dsc.h"

#ifndef FUNCNAME_DSCLOG_xml
#define FUNCNAME_DSCLOG_xml	DSCLOG_xml
#endif

#ifndef PREFIX_DSCLOG_xml
#define PREFIX_DSCLOG_xml	printf( 
#endif

#ifndef NEWLINE_DSCLOG_xml
#define NEWLINE_DSCLOG_xml	"\n"
#endif

int FUNCNAME_DSCLOG_xml( xml *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	PREFIX_DSCLOG_xml "xml.ToUserName[%s]" NEWLINE_DSCLOG_xml , pst->ToUserName );
	PREFIX_DSCLOG_xml "xml.FromUserName[%s]" NEWLINE_DSCLOG_xml , pst->FromUserName );
	PREFIX_DSCLOG_xml "xml.CreateTime[%d]" NEWLINE_DSCLOG_xml , pst->CreateTime );
	PREFIX_DSCLOG_xml "xml.MsgType[%s]" NEWLINE_DSCLOG_xml , pst->MsgType );
	PREFIX_DSCLOG_xml "xml.Content[%s]" NEWLINE_DSCLOG_xml , pst->Content );
	PREFIX_DSCLOG_xml "xml.Event[%s]" NEWLINE_DSCLOG_xml , pst->Event );
	PREFIX_DSCLOG_xml "xml.PicUrl[%s]" NEWLINE_DSCLOG_xml , pst->PicUrl );
	PREFIX_DSCLOG_xml "xml.MediaId[%s]" NEWLINE_DSCLOG_xml , pst->MediaId );
	PREFIX_DSCLOG_xml "xml.Format[%s]" NEWLINE_DSCLOG_xml , pst->Format );
	PREFIX_DSCLOG_xml "xml.Recognition[%s]" NEWLINE_DSCLOG_xml , pst->Recognition );
	PREFIX_DSCLOG_xml "xml.ThumbMediaId[%s]" NEWLINE_DSCLOG_xml , pst->ThumbMediaId );
	PREFIX_DSCLOG_xml "xml.Location_X[%lf]" NEWLINE_DSCLOG_xml , pst->Location_X );
	PREFIX_DSCLOG_xml "xml.Location_Y[%lf]" NEWLINE_DSCLOG_xml , pst->Location_Y );
	PREFIX_DSCLOG_xml "xml.Scale[%d]" NEWLINE_DSCLOG_xml , pst->Scale );
	PREFIX_DSCLOG_xml "xml.Label[%s]" NEWLINE_DSCLOG_xml , pst->Label );
	PREFIX_DSCLOG_xml "xml.Title[%s]" NEWLINE_DSCLOG_xml , pst->Title );
	PREFIX_DSCLOG_xml "xml.Description[%s]" NEWLINE_DSCLOG_xml , pst->Description );
	PREFIX_DSCLOG_xml "xml.Url[%s]" NEWLINE_DSCLOG_xml , pst->Url );
	PREFIX_DSCLOG_xml "xml.MsgId[%s]" NEWLINE_DSCLOG_xml , pst->MsgId );
	return 0;
}
